services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web3-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
    networks:
      - web3-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web3-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_DYNAMIC_ENVIRONMENT_ID=${VITE_DYNAMIC_ENVIRONMENT_ID}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
    networks:
      - web3-network
    depends_on:
      - backend

networks:
  web3-network:
    driver: bridge

