services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web3-backend-test
    environment:
      - NODE_ENV=test
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: bun test
    networks:
      - test-network

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web3-frontend-test
    environment:
      - NODE_ENV=test
      - VITE_DYNAMIC_ENVIRONMENT_ID=test-env-id
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: bun test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

